# Docker compose file version
version: "3.8"
services:
  db:
    # Define the image
    image: postgres:latest
    # Always restart if container stops
    restart: always
    # Define evs for the image
    environment:
      - POSTGRES_USER=jonkarrer
      - POSTGRES_PASSWORD=admin
    # Define the host/machine ports
    ports:
      - "5432:5432"
    # Path to store the data for the containers volumes
    volumes:
      # outside/inside, can change db to ./database to store right in root dir.
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local
